events {}

http {
    server {
        listen 80;

        location /api/auth/ {
            proxy_pass http://user-service:8001;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
        }

        location /api/users/ {
            proxy_pass http://user-service:8001;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
        }

        location /api/categories/ {
            proxy_pass http://product-service:8002;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
        }

        location /api/brands/ {
            proxy_pass http://product-service:8002;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
        }

        location /api/products/ {
            proxy_pass http://product-service:8002;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
        }

        location /api/cart/ {
            proxy_pass http://cart-service:8003;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
        }

        location /api/orders/ {
            proxy_pass http://order-service:8004;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
        }

        location /api/payments/ {
            proxy_pass http://payment-service:8005;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
        }

        location /api/ai/ {
            proxy_pass http://ai-service:5000;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://frontend:80;
            proxy_set_header Host $host;
        }
    }
}
